//#INCLUDE<IOSTREAM>
//#INCLUDE<STRING>
//
//USING NAMESPACE STD;
//
//CLASS STUDENT
//{
//PRIVATE:
//	STRING REGNO;
//PUBLIC:
//	VOID SETREGNO(STRING R) {
//		REGNO = R;
//	}
//	VOID SHOWREGNO()
//	{
//		COUT << "THE REGISTRATION NUMBER OF FOLLOWING STUDENTS ARE: " << REGNO << ENDL;
//	}
//
//};
//INT MAIN()
//{
//	STUDENT S1, S2, S3;
//
//	S1.SETREGNO("04071913018");
//	S2.SETREGNO("04071913019");
//	S3.SETREGNO("04071913020");
//
//	S1.SHOWREGNO();
//	S2.SHOWREGNO();
//	S3.SHOWREGNO();
//
//	RETURN 0;
//}